DOCS more information in changelog template
silverstripe/silverstripe-installer pull request #286
Opened 2020-08-26 04:33 UTC by brynwhyman

I've taken reference from the [4.6.1 change log](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.6.1.md) to use the 'CMS Recipe' table. 

The other information is taken from the existing CWP change log template, see: https://github.com/silverstripe/cwp-recipe-kitchen-sink/blob/2/.changelog.md.twig

2020-09-09 06:14 UTC, emteknetnz requested changes
A couple of minor edits

2020-09-09 06:14 UTC, emteknetnz commented on .cow/changelog.md.twig
> +A full list of module versions included in Recipe {{ version }} is provided below. We recommend referencing recipes in your dependencies, rather than individual modules, to simplify version tracking.
```suggestion
A full list of module versions included in CMS Recipe {{ version }} is provided below. We recommend referencing recipes in your dependencies, rather than individual modules, to simplify version tracking. See [Recipes](/getting_started/).
```

2020-09-09 06:14 UTC, emteknetnz commented on .cow/changelog.md.twig
> +| silverstripe/reports | x.x.x |
```suggestion
| silverstripe/mimevalidator | x.x.x |
| silverstripe/reports | x.x.x |
```
mimevalidator is now in recipe-core https://github.com/silverstripe/recipe-core/blob/4/composer.json#L12

2020-09-10 04:46 UTC, brynwhyman commented on .cow/changelog.md.twig
> +| silverstripe/reports | x.x.x |
Ah, nice catch!

2020-09-10 04:52 UTC, brynwhyman commented
@emteknetnz updated based on your suggestions.

2020-09-10 21:56 UTC, emteknetnz commented
Behat failures on travis are unrelated to this PR

2020-09-10 21:56 UTC, merged