MNT Use GitHub Actions CI
silverstripe/silverstripe-installer pull request #326
Opened 2022-06-29 22:09 UTC by emteknetnz

Issue https://github.com/silverstripe/gha-ci/issues/11

2022-07-15 02:27 UTC, GuySartorelli requested changes

2022-07-15 02:27 UTC, GuySartorelli commented on composer.json
> +        "mikey179/vfsstream": "^1.6.10"
This is already defined in gha-ci.yml as being included for _all_ runs.
We should either explicitly require it in composer.json for every repo that needs it and remove from gha-ci.yml, or else just accept that it's included in ci and not bother adding here.

2022-07-15 02:27 UTC, GuySartorelli commented on .github/workflows/ci.yml
> +      endtoend: false
travis config explicitly defines some behat tests which are not being run here

2022-07-15 02:27 UTC, GuySartorelli commented on composer.json
>      "require-dev": {
frameworktest and recipe-testing are defined in the travis config - are they needed here?

2022-07-17 22:08 UTC, emteknetnz commented on composer.json
> +        "mikey179/vfsstream": "^1.6.10"
Technically it should be in composer, say if you're actually running unit tests on your local.  There's an existing card https://github.com/silverstripe/gha-ci/issues/6 to add it to composer.json

2022-07-17 22:13 UTC, emteknetnz commented on .github/workflows/ci.yml
> +      endtoend: false
updated

2022-07-17 22:15 UTC, emteknetnz commented on composer.json
>      "require-dev": {
yup, updated

2022-07-17 22:22 UTC, GuySartorelli approved these changes

2022-07-17 22:22 UTC, merged