MNT Test additional modules
silverstripe/silverstripe-installer pull request #348
Opened 2023-01-25 21:05 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/660

2023-01-25 22:53 UTC, GuySartorelli requested changes

2023-01-25 22:53 UTC, GuySartorelli commented on phpunit.xml.dist
> +            <directory>vendor/silverstripe/config/tests/</directory>
config seems like core to me

2023-01-25 22:53 UTC, GuySartorelli commented on phpunit.xml.dist
> +            <directory>vendor/silverstripe/login-forms/tests/php/</directory>
errorpage and login-forms aren't admin - they aren't in the /admin space at all. They should go in a new testsuite perhaps.

2023-01-26 01:05 UTC, emteknetnz commented
The testsuite names are completely arbitrary and in practice they'll never be run separately.  Their actual purpose is to is to facilitate parallel testing in CI

The "admin" testsuite takes the least amount of time to run right now, so it makes sense to add the new directories there

I don't want to add a new testsuite because we there's already 14 jobs being created due to the 3 PHP versions.  Also there's little point since framework alone takes 18 minutes https://github.com/silverstripe/silverstripe-installer/actions/runs/4010055028/jobs/6886120318 so the overall action won't be any faster

2023-01-26 01:09 UTC, GuySartorelli commented
> The testsuite names are completely arbitrary

They're not, though? Like... it's fairly obvious that "admin" is "this stuff is in /admin".

But whatever, I'll just merge it.

2023-01-26 01:09 UTC, merged