API Remove GraphQL
silverstripe/silverstripe-installer pull request #375
Opened 2024-07-30 07:29 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1799

2024-08-20 03:25 UTC, GuySartorelli requested changes

2024-08-20 03:25 UTC, GuySartorelli commented on .gitignore
> -/public/_graphql/
We should probably keep these - people using public schemas shouldn't suddenly find their new projects are adding these to their git repos.

Alternatively we should make absolutely sure this is called out in the graphql docs early on.

2024-08-20 03:25 UTC, GuySartorelli commented on composer.json
> +            ".env.example"
We should either keep this (along with the folder, which I note you haven't deleted) - or else make sure the manifest exclude file gets generated by silverstripe/graphql itself.

2024-08-21 03:34 UTC, emteknetnz commented on .gitignore
> -/public/_graphql/
Reverted

2024-08-21 03:35 UTC, emteknetnz commented on composer.json
> +            ".env.example"
Reverted

2024-08-22 05:05 UTC, GuySartorelli approved these changes
LGTM, will merge when other PRs are happy

2024-09-02 04:33 UTC, merged